version: '3.3'
services:
  # web:
  #     build: .
  #     volumes:
  #     - .:/app
  #     - ~/.m2:/root/.m2
  #     working_dir: /app
  #     ports:
  #     - 8080:8080
  #     command: mvn clean spring-boot:run
  #     depends_on:
  #     - db
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "springuser"
      MYSQL_PASSWORD: "ThePassword"
      MYSQL_DATABASE: "MySQL_alms_box"
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql/db_example:/alms_box
